# SITE CONFIGURATION
baseurl: "/Hemal Dey"
url: "https://Hemal Dey.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Hemal Dey's CV                                    # site's title
description: "A website Hemal Dey's CV"      # used by search engines
